### ISSUE TITLE
Fresh install gives errors

### ISSUE THREAD

**Issue by godlevel** [atrauzzi/laravel-doctrine#78]
I installed the package exactly as the readme says, but I can't get it to work. When I run `vendor/bin/doctrine` in my command line I get errors. Can someone help me?

```
My stack trace:
[2015-05-05 15:16:53] local.ERROR: exception 'ErrorException' with message 'Argument 2 passed to Symfony\Component\Debug\Exception\ClassNotFoundException::__construct() must be an instance of ErrorException, null given, called in /Users/Angelo/Code/klix/vendor/atrauzzi/laravel-doctrine/src/CacheFactory.php on line 31 and defined' in /Users/Angelo/Code/klix/vendor/symfony/debug/Symfony/Component/Debug/Exception/ClassNotFoundException.php:21

Stack trace:
#0 /Users/Angelo/Code/klix/vendor/symfony/debug/Symfony/Component/Debug/Exception/ClassNotFoundException.php(21): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(4096, 'Argument 2 pass...', '/Users/Angelo/C...', 21, Array)

#1 /Users/Angelo/Code/klix/vendor/atrauzzi/laravel-doctrine/src/CacheFactory.php(31): Symfony\Component\Debug\Exception\ClassNotFoundException->__construct('Class not found...', NULL)

#2 /Users/Angelo/Code/klix/vendor/atrauzzi/laravel-doctrine/src/ServiceProvider.php(221): Atrauzzi\LaravelDoctrine\CacheFactory::getCacheProvider('array', 'laravel')

#3 /Users/Angelo/Code/klix/vendor/atrauzzi/laravel-doctrine/src/ServiceProvider.php(48): Atrauzzi\LaravelDoctrine\ServiceProvider->createCache()

#4 /Users/Angelo/Code/klix/vendor/laravel/framework/src/Illuminate/Container/Container.php(773): Atrauzzi\LaravelDoctrine\ServiceProvider->Atrauzzi\LaravelDoctrine\{closure}(Object(Illuminate\Foundation\Application), Array)

#5 /Users/Angelo/Code/klix/vendor/laravel/framework/src/Illuminate/Container/Container.php(656): Illuminate\Container\Container->build(Object(Closure), Array)

#6 /Users/Angelo/Code/klix/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(644): Illuminate\Container\Container->make('Doctrine\\ORM\\En...', Array)

#7 /Users/Angelo/Code/klix/cli-config.php(16): Illuminate\Foundation\Application->make('Doctrine\\ORM\\En...')

#8 /Users/Angelo/Code/klix/vendor/doctrine/orm/bin/doctrine.php(55): require('/Users/Angelo/C...')

#9 /Users/Angelo/Code/klix/vendor/doctrine/orm/bin/doctrine(4): include('/Users/Angelo/C...')

#10 {main}  
```

**Comment by mbbender** [comment]
Did you publish the config file? Do you have a 'cache' section in your doctrine.php config file?

**Comment by godlevel** [comment]
Oh man, sorry, I should read comments more often. Thanks for the info @mbbender
